version: "3.9"
services:
  web:
    build: .
    depends_on:
      - "mongodb"
    links:
      - mongodb
    ports:
      - "5000:5000"
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root


